// <auto-generated />
namespace ERAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MoreTransformationDataObjects2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreTransformationDataObjects2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808031858249_More Transformation Data Objects2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
